
CREATE DATABASE IF NOT EXISTS jdbc_test_db;

USE jdbc_test_db;
-- 用户账户表
CREATE TABLE IF NOT EXISTS t_user_account(
user_id VARCHAR(64) NOT NULL COMMENT '用户id',
username VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
password VARCHAR(64) NOT NULL DEFAULT '' COMMENT '密码',
avatar VARCHAR(100) NOT NULL DEFAULT '' COMMENT '头像路径',
nickname VARCHAR(20) NOT NULL DEFAULT '' COMMENT '昵称',
gender TINYINT NOT NULL DEFAULT 0 COMMENT '性别 1=男，2=女',
birthday VARCHAR(10) NOT NULL DEFAULT '0000-00-00' COMMENT '生日',
state TINYINT NOT NULL DEFAULT 0  COMMENT '状态 0=使用中，1=注销',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(user_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT '用户账户表';